[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
size = 11.0

[window]
opacity = 0.90
padding = { x = 10, y = 10 }
decorations = "None" # Minimalist look

[colors.primary]
background = "#11111b"
foreground = "#cdd6f4"
